do not create a child Vault token
Might be the cause of the errors we're seeing:

```
Error: Provider produced inconsistent result after apply
When applying changes to module.tfc-auth.tfe_variable.tfc_workspace_vault_auth_path["vault-config"], provider "provider[\"registry.terraform.io/hashicorp/tfe\"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```